version: '3.1'

services:
  db:
    image: mysql
    ports:
      - 8001:3306
    restart: always
    environment:
      - MYSQL_DATABASE=urlshortener
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=pword
      - MYSQL_ROOT_PASSWORD=SOMEpword
  
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app