# Generated by Django 4.0.3 on 2022-03-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=500, unique=True)),
                ('original_url', models.URLField(max_length=500)),
                ('times_used', models.IntegerField(default=0)),
            ],
        ),
    ]
